### ISSUE TITLE
Missing debug symbols

### ISSUE THREAD

**Issue by thiblahute** [alexlarsson/gnome-sdk-images#15]
I got the Debug runtime installed:

```
$ xdg-app list --user --runtime                           
org.freedesktop.Platform    
org.freedesktop.Sdk         
org.gnome.Debug             
org.gnome.Platform.Locale.en
org.gnome.Platform          
org.gnome.Sdk.Locale.en     
org.gnome.Sdk               
```

But I am still missing python/pygi... and more debug symbols:

```
[ptv] thiblahute ~/devel/pitivi/xdg-app/pitivi (T7324-fix_loading_project_missing_assets) $ G_DEBUG=fatal-criticals gdb --args python3 /app/bin/nosetests  tests/*.py
GNU gdb (GDB) 7.8.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-freedesktop-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
No symbol table is loaded.  Use the "file" command.
Breakpoint 1 (send_failure_info) pending.
Reading symbols from python3...(no debugging symbols found)...done.
(gdb) r
Starting program: /usr/bin/python3 /app/bin/nosetests tests/__init__.py tests/common.py tests/runtests.py tests/test_application.py tests/test_check.py tests/test_clipproperties.py tests/test_common.py tests/test_log.py tests/test_mainwindow.py tests/test_media_library.py tests/test_misc.py tests/test_pipeline.py tests/test_prefs.py tests/test_preset.py tests/test_previewers.py tests/test_project.py tests/test_system.py tests/test_timeline_layer.py tests/test_timeline_timeline.py tests/test_undo.py tests/test_undo_timeline.py tests/test_utils.py tests/test_utils_timeline.py tests/test_widgets.py
warning: Error disabling address space randomization: Operation not permitted
warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/libthread_db.so.1".
[New Thread 0x7f077d4c3700 (LWP 62)]
[New Thread 0x7f077ccc2700 (LWP 63)]
[New Thread 0x7f0777fff700 (LWP 64)]

[New Thread 0x7f07380fc700 (LWP 65)]
...........................Gtk-Message: Failed to load module "canberra-gtk-module"
.[New Thread 0x7f073773b700 (LWP 66)]
[New Thread 0x7f0736f3a700 (LWP 67)]
[New Thread 0x7f0736739700 (LWP 68)]
[New Thread 0x7f0735f38700 (LWP 69)]
[New Thread 0x7f0735737700 (LWP 70)]
[New Thread 0x7f0734f36700 (LWP 71)]
[New Thread 0x7f0717fff700 (LWP 72)]
[New Thread 0x7f07177fe700 (LWP 73)]
[New Thread 0x7f0716ffd700 (LWP 74)]
[New Thread 0x7f07167fc700 (LWP 75)]
[New Thread 0x7f0715ffb700 (LWP 76)]
[Thread 0x7f0715ffb700 (LWP 76) exited]
[New Thread 0x7f07157fa700 (LWP 77)]
[New Thread 0x7f0715ffb700 (LWP 78)]
[New Thread 0x7f0714ff9700 (LWP 79)]
[Thread 0x7f0714ff9700 (LWP 79) exited]

** (nosetests:58): WARNING **: Unhandled type tag GType

(nosetests:58): Gtk-CRITICAL **: gtk_revealer_set_reveal_child: assertion 'GTK_IS_REVEALER (revealer)' failed

Program received signal SIGTRAP, Trace/breakpoint trap.
g_logv (log_domain=0x7f077f177c58 "Gtk", log_level=G_LOG_LEVEL_CRITICAL, format=<optimized out>, args=args@entry=0x7ffe4ce8e688) at gmessages.c:1086
1086    gmessages.c: No such file or directory.
(gdb) 
(gdb) bt
#0  g_logv (log_domain=0x7f077f177c58 "Gtk", log_level=G_LOG_LEVEL_CRITICAL, format=<optimized out>, args=args@entry=0x7ffe4ce8e688) at gmessages.c:1086
#1  0x00007f07874d6722 in g_log (log_domain=<optimized out>, log_level=<optimized out>, format=<optimized out>) at gmessages.c:1119
#2  0x00007f07877cc525 in g_closure_invoke (closure=closure@entry=0x2b58040, return_value=return_value@entry=0x0, n_param_values=1, param_values=param_values@entry=0x7ffe4ce8e920, invocation_hint=invocation_hint@entry=0x7ffe4ce8e8c0) at gclosure.c:801
#3  0x00007f07877dd9f4 in signal_emit_unlocked_R (node=node@entry=0x2b6b830, detail=detail@entry=0, instance=instance@entry=0x3ca0760, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7ffe4ce8e920) at gsignal.c:3557
#4  0x00007f07877e6986 in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7ffe4ce8ea98) at gsignal.c:3383
#5  0x00007f07877e6bb2 in g_signal_emit (instance=instance@entry=0x3ca0760, signal_id=<optimized out>, detail=detail@entry=0) at gsignal.c:3439
#6  0x00007f077f13a845 in gtk_widget_show (widget=0x3ca0760) at gtkwidget.c:4726
#7  0x00007f0787284d86 in ffi_call_unix64 () from /lib/libffi.so.6
#8  0x00007f0787284862 in ffi_call () from /lib/libffi.so.6
#9  0x00007f0787e6be44 in ?? () from /usr/lib/python3.3/site-packages/gi/_gi.cpython-33m.so
#10 0x00007f0787e6d7ea in ?? () from /usr/lib/python3.3/site-packages/gi/_gi.cpython-33m.so
#11 0x00007f0787e627ae in ?? () from /usr/lib/python3.3/site-packages/gi/_gi.cpython-33m.so
#12 0x00007f078dab1e78 in PyObject_Call () from /lib/libpython3.3m.so.1.0
#13 0x00007f078db50207 in ?? () from /lib/libpython3.3m.so.1.0
#14 0x00007f078db549ce in ?? () from /lib/libpython3.3m.so.1.0
#15 0x00007f078db515c9 in PyEval_EvalFrameEx () from /lib/libpython3.3m.so.1.0
#16 0x00007f078db54746 in PyEval_EvalCodeEx () from /lib/libpython3.3m.so.1.0
#17 0x00007f078db547f4 in ?? () from /lib/libpython3.3m.so.1.0
#18 0x00007f078db54a3f in ?? () from /lib/libpython3.3m.so.1.0
#19 0x00007f078db515c9 in PyEval_EvalFrameEx () from /lib/libpython3.3m.so.1.0
#20 0x00007f078db54746 in PyEval_EvalCodeEx () from /lib/libpython3.3m.so.1.0
#21 0x00007f078dad48c5 in ?? () from /lib/libpython3.3m.so.1.0
#22 0x00007f078dab1e78 in PyObject_Call () from /lib/libpython3.3m.so.1.0
#23 0x00007f078dac24bf in ?? () from /lib/libpython3.3m.so.1.0
#24 0x00007f078dab1e78 in PyObject_Call () from /lib/libpython3.3m.so.1.0
#25 0x00007f078db4fe77 in PyEval_CallObjectWithKeywords () from /lib/libpython3.3m.so.1.0
#26 0x00007f0787e5d29d in ?? () from /usr/lib/python3.3/site-packages/gi/_gi.cpython-33m.so
#27 0x00007f07877cc525 in g_closure_invoke (closure=0x3ba1730, return_value=return_value@entry=0x7ffe4ce8f750, n_param_values=3, param_values=param_values@entry=0x3cc7900, invocation_hint=invocation_hint@entry=0x7ffe4ce8f650) at gclosure.c:801
#28 0x00007f07877de0d1 in signal_emit_unlocked_R (node=node@entry=0x37b2630, detail=detail@entry=0, instance=instance@entry=0x38cfb80, emission_return=emission_return@entry=0x7ffe4ce8f750, instance_and_params=instance_and_params@entry=0x3cc7900) at gsignal.c:3627
#29 0x00007f07877e5921 in g_signal_emitv (instance_and_params=0x3cc7900, signal_id=<optimized out>, detail=0, return_value=0x7ffe4ce8f750) at gsignal.c:3122
#30 0x00007f0787e587d2 in ?? () from /usr/lib/python3.3/site-packages/gi/_gi.cpython-33m.so
#31 0x00007f078db54b1d in ?? () from /lib/libpython3.3m.so.1.0
#32 0x00007f078db515c9 in PyEval_EvalFrameEx () from /lib/libpython3.3m.so.1.0
#33 0x00007f078db54746 in PyEval_EvalCodeEx () from /lib/libpython3.3m.so.1.0
#34 0x00007f078dad48c5 in ?? () from /lib/libpython3.3m.so.1.0
#35 0x00007f078dab1e78 in PyObject_Call () from /lib/libpython3.3m.so.1.0
#36 0x00007f078dac24bf in ?? () from /lib/libpython3.3m.so.1.0
#37 0x00007f078dab1e78 in PyObject_Call () from /lib/libpython3.3m.so.1.0
#38 0x00007f078db4fe77 in PyEval_CallObjectWithKeywords () from /lib/libpython3.3m.so.1.0
#39 0x00007f0787e6b170 in ?? () from /usr/lib/python3.3/site-packages/gi/_gi.cpython-33m.so
#40 0x00007f07877cc525 in g_closure_invoke (closure=0x3f90cc0, return_value=return_value@entry=0x0, n_param_values=2, param_values=param_values@entry=0x7ffe4ce8ff50, invocation_hint=invocation_hint@entry=0x7ffe4ce8fef0) at gclosure.c:801
#41 0x00007f07877de0d1 in signal_emit_unlocked_R (node=node@entry=0x37b4800, detail=detail@entry=0, instance=instance@entry=0x28aac00, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7ffe4ce8ff50) at gsignal.c:3627
#42 0x00007f07877e6986 in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7ffe4ce900d8) at gsignal.c:3383
#43 0x00007f07877e6bb2 in g_signal_emit (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>) at gsignal.c:3439
#44 0x00007f0780f404fb in ges_project_set_loaded (project=0x28aac00, formatter=0x3c8ebf0) at ges-project.c:661
#45 0x00007f0780f42c3f in new_asset_cb (source=0x39f3620, res=0x0, passet=0x0) at ges-base-xml-formatter.c:792
#46 0x00007f0786d834e3 in g_task_return_now (task=0x406a680) at gtask.c:1106
#47 0x00007f0786d83b5e in g_task_return (task=0x406a680, type=<optimized out>) at gtask.c:1164
#48 0x00007f07874cc4dd in g_list_foreach (list=<optimized out>, func=0x7f0780f3a4f0 <_gtask_return_error>, user_data=0x3c54530) at glist.c:1005
#49 0x00007f0780f3ace1 in ges_asset_cache_set_loaded (extractable_type=60774048, id=0x7f07816ae880 <_gst_debug_min> "\001", error=0x3c54530) at ges-asset.c:556
#50 0x00007f0780f3db6f in discoverer_discovered_cb (discoverer=<optimized out>, info=<optimized out>, err=0x3c54520, user_data=<optimized out>) at ges-uri-asset.c:370
#51 0x00007f0787284d86 in ffi_call_unix64 () from /lib/libffi.so.6
#52 0x00007f0787284862 in ffi_call () from /lib/libffi.so.6
#53 0x00007f07877ccd14 in g_cclosure_marshal_generic (closure=0x3d0f7d0, return_gvalue=0x0, n_param_values=<optimized out>, param_values=<optimized out>, invocation_hint=<optimized out>, marshal_data=0x0) at gclosure.c:1487
#54 0x00007f07877cc525 in g_closure_invoke (closure=0x3d0f7d0, return_value=return_value@entry=0x0, n_param_values=3, param_values=param_values@entry=0x7ffe4ce90740, invocation_hint=invocation_hint@entry=0x7ffe4ce906e0) at gclosure.c:801
#55 0x00007f07877de0d1 in signal_emit_unlocked_R (node=node@entry=0x3f98660, detail=detail@entry=0, instance=instance@entry=0x2e30dd0, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7ffe4ce90740) at gsignal.c:3627
#56 0x00007f07877e6986 in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7ffe4ce908e8) at gsignal.c:3383
#57 0x00007f07877e6bb2 in g_signal_emit (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>) at gsignal.c:3439
#58 0x00007f0780543dc0 in ?? () from /app/lib/libgstpbutils-1.0.so.0
#59 0x00007f07805441f1 in ?? () from /app/lib/libgstpbutils-1.0.so.0
#60 0x00007f07877cf2e3 in g_cclosure_marshal_VOID__BOXEDv (closure=0x3efd220, return_value=<optimized out>, instance=<optimized out>, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0x29848a0) at gmarshal.c:1950
#61 0x00007f07877cc754 in _g_closure_invoke_va (closure=0x0, closure@entry=0x3efd220, return_value=return_value@entry=0x0, instance=0x0, instance@entry=0x406a530, args=0x7f078d78b24d <write+45>, args@entry=0x7ffe4ce90c48, n_params=32768, param_types=0xf) at gclosure.c:864
#62 0x00007f07877e6298 in g_signal_emit_valist (instance=0x406a530, signal_id=<optimized out>, detail=203, var_args=var_args@entry=0x7ffe4ce90c48) at gsignal.c:3292
#63 0x00007f07877e6bb2 in g_signal_emit (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>) at gsignal.c:3439
#64 0x00007f07813c6982 in gst_bus_async_signal_func () from /app/lib/libgstreamer-1.0.so.0
#65 0x00007f07813c77a6 in ?? () from /app/lib/libgstreamer-1.0.so.0
#66 0x00007f07874cfe2d in g_main_dispatch (context=0x28b7640) at gmain.c:3154
#67 g_main_context_dispatch (context=context@entry=0x28b7640) at gmain.c:3769
#68 0x00007f07874d01c8 in g_main_context_iterate (context=0x28b7640, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3840
#69 0x00007f07874d04e2 in g_main_loop_run (loop=0x3d467f0) at gmain.c:4034
#70 0x00007f0787284d86 in ffi_call_unix64 () from /lib/libffi.so.6
#71 0x00007f0787284862 in ffi_call () from /lib/libffi.so.6
#72 0x00007f0787e6be44 in ?? () from /usr/lib/python3.3/site-packages/gi/_gi.cpython-33m.so
#73 0x00007f0787e6d7ea in ?? () from /usr/lib/python3.3/site-packages/gi/_gi.cpython-33m.so
#74 0x00007f0787e627ae in ?? () from /usr/lib/python3.3/site-packages/gi/_gi.cpython-33m.so
#75 0x00007f078dab1e78 in PyObject_Call () from /lib/libpython3.3m.so.1.0
#76 0x00007f078db50207 in ?? () from /lib/libpython3.3m.so.1.0
#77 0x00007f078db549ce in ?? () from /lib/libpython3.3m.so.1.0
#78 0x00007f078db515c9 in PyEval_EvalFrameEx () from /lib/libpython3.3m.so.1.0
#79 0x00007f078db54746 in PyEval_EvalCodeEx () from /lib/libpython3.3m.so.1.0
#80 0x00007f078db547f4 in ?? () from /lib/libpython3.3m.so.1.0
#81 0x00007f078db54a3f in ?? () from /lib/libpython3.3m.so.1.0
#82 0x00007f078db515c9 in PyEval_EvalFrameEx () from /lib/libpython3.3m.so.1.0
#83 0x00007f078db54746 in PyEval_EvalCodeEx () from /lib/libpython3.3m.so.1.0
#84 0x00007f078db547f4 in ?? () from /lib/libpython3.3m.so.1.0
#85 0x00007f078db54a3f in ?? () from /lib/libpython3.3m.so.1.0
#86 0x00007f078db515c9 in PyEval_EvalFrameEx () from /lib/libpython3.3m.so.1.0
#87 0x00007f078db5488f in ?? () from /lib/libpython3.3m.so.1.0
#88 0x00007f078db54a3f in ?? () from /lib/libpython3.3m.so.1.0
#89 0x00007f078db515c9 in PyEval_EvalFrameEx () from /lib/libpython3.3m.so.1.0
#90 0x00007f078db54746 in PyEval_EvalCodeEx () from /lib/libpython3.3m.so.1.0
#91 0x00007f078db547f4 in ?? () from /lib/libpython3.3m.so.1.0
#92 0x00007f078db54a3f in ?? () from /lib/libpython3.3m.so.1.0
#93 0x00007f078db515c9 in PyEval_EvalFrameEx () from /lib/libpython3.3m.so.1.0
#94 0x00007f078db54746 in PyEval_EvalCodeEx () from /lib/libpython3.3m.so.1.0
#95 0x00007f078db547f4 in ?? () from /lib/libpython3.3m.so.1.0
#96 0x00007f078db54a3f in ?? () from /lib/libpython3.3m.so.1.0
#97 0x00007f078db515c9 in PyEval_EvalFrameEx () from /lib/libpython3.3m.so.1.0
#98 0x00007f078db54746 in PyEval_EvalCodeEx () from /lib/libpython3.3m.so.1.0
#99 0x00007f078dad49a6 in ?? () from /lib/libpython3.3m.so.1.0
#100 0x00007f078dab1e78 in PyObject_Call () from /lib/libpython3.3m.so.1.0
#101 0x00007f078db5040b in ?? () from /lib/libpython3.3m.so.1.0
#102 0x00007f078db517d0 in PyEval_EvalFrameEx () from /lib/libpython3.3m.so.1.0
#103 0x00007f078db54746 in PyEval_EvalCodeEx () from /lib/libpython3.3m.so.1.0
#104 0x00007f078dad48c5 in ?? () from /lib/libpython3.3m.so.1.0
#105 0x00007f078dab1e78 in PyObject_Call () from /lib/libpython3.3m.so.1.0
#106 0x00007f078dac24bf in ?? () from /lib/libpython3.3m.so.1.0
#107 0x00007f078dab1e78 in PyObject_Call () from /lib/libpython3.3m.so.1.0
#108 0x00007f078db01870 in ?? () from /lib/libpython3.3m.so.1.0
#109 0x00007f078dab1e78 in PyObject_Call () from /lib/libpython3.3m.so.1.0
#110 0x00007f078db50207 in ?? () from /lib/libpython3.3m.so.1.0
#111 0x00007f078db549ce in ?? () from /lib/libpython3.3m.so.1.0
#112 0x00007f078db515c9 in PyEval_EvalFrameEx () from /lib/libpython3.3m.so.1.0
#113 0x00007f078db5488f in ?? () from /lib/libpython3.3m.so.1.0
#114 0x00007f078db54a3f in ?? () from /lib/libpython3.3m.so.1.0
#115 0x00007f078db515c9 in PyEval_EvalFrameEx () from /lib/libpython3.3m.so.1.0
#116 0x00007f078db54746 in PyEval_EvalCodeEx () from /lib/libpython3.3m.so.1.0
#117 0x00007f078dad49a6 in ?? () from /lib/libpython3.3m.so.1.0
#118 0x00007f078dab1e78 in PyObject_Call () from /lib/libpython3.3m.so.1.0
#119 0x00007f078db5040b in ?? () from /lib/libpython3.3m.so.1.0
#120 0x00007f078db517d0 in PyEval_EvalFrameEx () from /lib/libpython3.3m.so.1.0
#121 0x00007f078db54746 in PyEval_EvalCodeEx () from /lib/libpython3.3m.so.1.0
#122 0x00007f078dad48c5 in ?? () from /lib/libpython3.3m.so.1.0
#123 0x00007f078dab1e78 in PyObject_Call () from /lib/libpython3.3m.so.1.0
#124 0x00007f078dac24bf in ?? () from /lib/libpython3.3m.so.1.0
#125 0x00007f078dab1e78 in PyObject_Call () from /lib/libpython3.3m.so.1.0
#126 0x00007f078db01870 in ?? () from /lib/libpython3.3m.so.1.0
#127 0x00007f078dab1e78 in PyObject_Call () from /lib/libpython3.3m.so.1.0
#128 0x00007f078db50207 in ?? () from /lib/libpython3.3m.so.1.0
#129 0x00007f078db549ce in ?? () from /lib/libpython3.3m.so.1.0
#130 0x00007f078db515c9 in PyEval_EvalFrameEx () from /lib/libpython3.3m.so.1.0
#131 0x00007f078db54746 in PyEval_EvalCodeEx () from /lib/libpython3.3m.so.1.0
#132 0x00007f078dad49a6 in ?? () from /lib/libpython3.3m.so.1.0
#133 0x00007f078dab1e78 in PyObject_Call () from /lib/libpython3.3m.so.1.0
#134 0x00007f078db5040b in ?? () from /lib/libpython3.3m.so.1.0
#135 0x00007f078db517d0 in PyEval_EvalFrameEx () from /lib/libpython3.3m.so.1.0
#136 0x00007f078db54746 in PyEval_EvalCodeEx () from /lib/libpython3.3m.so.1.0
#137 0x00007f078dad48c5 in ?? () from /lib/libpython3.3m.so.1.0
#138 0x00007f078dab1e78 in PyObject_Call () from /lib/libpython3.3m.so.1.0
#139 0x00007f078dac24bf in ?? () from /lib/libpython3.3m.so.1.0
#140 0x00007f078dab1e78 in PyObject_Call () from /lib/libpython3.3m.so.1.0
#141 0x00007f078db01870 in ?? () from /lib/libpython3.3m.so.1.0
#142 0x00007f078dab1e78 in PyObject_Call () from /lib/libpython3.3m.so.1.0
#143 0x00007f078db50207 in ?? () from /lib/libpython3.3m.so.1.0
#144 0x00007f078db549ce in ?? () from /lib/libpython3.3m.so.1.0
#145 0x00007f078db515c9 in PyEval_EvalFrameEx () from /lib/libpython3.3m.so.1.0
#146 0x00007f078db54746 in PyEval_EvalCodeEx () from /lib/libpython3.3m.so.1.0
#147 0x00007f078dad49a6 in ?? () from /lib/libpython3.3m.so.1.0
#148 0x00007f078dab1e78 in PyObject_Call () from /lib/libpython3.3m.so.1.0
#149 0x00007f078db5040b in ?? () from /lib/libpython3.3m.so.1.0
#150 0x00007f078db517d0 in PyEval_EvalFrameEx () from /lib/libpython3.3m.so.1.0
#151 0x00007f078db54746 in PyEval_EvalCodeEx () from /lib/libpython3.3m.so.1.0
#152 0x00007f078dad48c5 in ?? () from /lib/libpython3.3m.so.1.0
#153 0x00007f078dab1e78 in PyObject_Call () from /lib/libpython3.3m.so.1.0
#154 0x00007f078dac24bf in ?? () from /lib/libpython3.3m.so.1.0
#155 0x00007f078dab1e78 in PyObject_Call () from /lib/libpython3.3m.so.1.0
#156 0x00007f078db01870 in ?? () from /lib/libpython3.3m.so.1.0
#157 0x00007f078dab1e78 in PyObject_Call () from /lib/libpython3.3m.so.1.0
#158 0x00007f078db50207 in ?? () from /lib/libpython3.3m.so.1.0
#159 0x00007f078db549ce in ?? () from /lib/libpython3.3m.so.1.0
#160 0x00007f078db515c9 in PyEval_EvalFrameEx () from /lib/libpython3.3m.so.1.0
#161 0x00007f078db54746 in PyEval_EvalCodeEx () from /lib/libpython3.3m.so.1.0
#162 0x00007f078dad49a6 in ?? () from /lib/libpython3.3m.so.1.0
#163 0x00007f078dab1e78 in PyObject_Call () from /lib/libpython3.3m.so.1.0
#164 0x00007f078db5040b in ?? () from /lib/libpython3.3m.so.1.0
#165 0x00007f078db517d0 in PyEval_EvalFrameEx () from /lib/libpython3.3m.so.1.0
#166 0x00007f078db54746 in PyEval_EvalCodeEx () from /lib/libpython3.3m.so.1.0
#167 0x00007f078dad48c5 in ?? () from /lib/libpython3.3m.so.1.0
#168 0x00007f078dab1e78 in PyObject_Call () from /lib/libpython3.3m.so.1.0
#169 0x00007f078dac24bf in ?? () from /lib/libpython3.3m.so.1.0
#170 0x00007f078dab1e78 in PyObject_Call () from /lib/libpython3.3m.so.1.0
#171 0x00007f078db01870 in ?? () from /lib/libpython3.3m.so.1.0
#172 0x00007f078dab1e78 in PyObject_Call () from /lib/libpython3.3m.so.1.0
#173 0x00007f078db50207 in ?? () from /lib/libpython3.3m.so.1.0
#174 0x00007f078db549ce in ?? () from /lib/libpython3.3m.so.1.0
#175 0x00007f078db515c9 in PyEval_EvalFrameEx () from /lib/libpython3.3m.so.1.0
#176 0x00007f078db54746 in PyEval_EvalCodeEx () from /lib/libpython3.3m.so.1.0
#177 0x00007f078dad49a6 in ?? () from /lib/libpython3.3m.so.1.0
#178 0x00007f078dab1e78 in PyObject_Call () from /lib/libpython3.3m.so.1.0
#179 0x00007f078db5040b in ?? () from /lib/libpython3.3m.so.1.0
#180 0x00007f078db517d0 in PyEval_EvalFrameEx () from /lib/libpython3.3m.so.1.0
#181 0x00007f078db54746 in PyEval_EvalCodeEx () from /lib/libpython3.3m.so.1.0
#182 0x00007f078dad48c5 in ?? () from /lib/libpython3.3m.so.1.0
#183 0x00007f078dab1e78 in PyObject_Call () from /lib/libpython3.3m.so.1.0
#184 0x00007f078dac24bf in ?? () from /lib/libpython3.3m.so.1.0
#185 0x00007f078dab1e78 in PyObject_Call () from /lib/libpython3.3m.so.1.0
#186 0x00007f078db01870 in ?? () from /lib/libpython3.3m.so.1.0
#187 0x00007f078dab1e78 in PyObject_Call () from /lib/libpython3.3m.so.1.0
#188 0x00007f078db50207 in ?? () from /lib/libpython3.3m.so.1.0
#189 0x00007f078db549ce in ?? () from /lib/libpython3.3m.so.1.0
#190 0x00007f078db515c9 in PyEval_EvalFrameEx () from /lib/libpython3.3m.so.1.0
#191 0x00007f078db5488f in ?? () from /lib/libpython3.3m.so.1.0
#192 0x00007f078db54a3f in ?? () from /lib/libpython3.3m.so.1.0
#193 0x00007f078db515c9 in PyEval_EvalFrameEx () from /lib/libpython3.3m.so.1.0
#194 0x00007f078db5488f in ?? () from /lib/libpython3.3m.so.1.0
#195 0x00007f078db54a3f in ?? () from /lib/libpython3.3m.so.1.0
#196 0x00007f078db515c9 in PyEval_EvalFrameEx () from /lib/libpython3.3m.so.1.0
#197 0x00007f078db54746 in PyEval_EvalCodeEx () from /lib/libpython3.3m.so.1.0
#198 0x00007f078dad49a6 in ?? () from /lib/libpython3.3m.so.1.0
#199 0x00007f078dab1e78 in PyObject_Call () from /lib/libpython3.3m.so.1.0
#200 0x00007f078db5040b in ?? () from /lib/libpython3.3m.so.1.0
#201 0x00007f078db517d0 in PyEval_EvalFrameEx () from /lib/libpython3.3m.so.1.0
#202 0x00007f078db54746 in PyEval_EvalCodeEx () from /lib/libpython3.3m.so.1.0
#203 0x00007f078dad48c5 in ?? () from /lib/libpython3.3m.so.1.0
#204 0x00007f078dab1e78 in PyObject_Call () from /lib/libpython3.3m.so.1.0
#205 0x00007f078dac24bf in ?? () from /lib/libpython3.3m.so.1.0
#206 0x00007f078dab1e78 in PyObject_Call () from /lib/libpython3.3m.so.1.0
#207 0x00007f078db015e0 in ?? () from /lib/libpython3.3m.so.1.0
#208 0x00007f078daffb96 in ?? () from /lib/libpython3.3m.so.1.0
#209 0x00007f078dab1e78 in PyObject_Call () from /lib/libpython3.3m.so.1.0
#210 0x00007f078db50207 in ?? () from /lib/libpython3.3m.so.1.0
#211 0x00007f078db549ce in ?? () from /lib/libpython3.3m.so.1.0
#212 0x00007f078db515c9 in PyEval_EvalFrameEx () from /lib/libpython3.3m.so.1.0
#213 0x00007f078db54746 in PyEval_EvalCodeEx () from /lib/libpython3.3m.so.1.0
#214 0x00007f078db5478b in PyEval_EvalCode () from /lib/libpython3.3m.so.1.0
#215 0x00007f078db6e804 in ?? () from /lib/libpython3.3m.so.1.0
#216 0x00007f078db70150 in PyRun_FileExFlags () from /lib/libpython3.3m.so.1.0
#217 0x00007f078db70e11 in PyRun_SimpleFileExFlags () from /lib/libpython3.3m.so.1.0
#218 0x00007f078db81e21 in ?? () from /lib/libpython3.3m.so.1.0
#219 0x00007f078db82856 in Py_Main () from /lib/libpython3.3m.so.1.0
#220 0x0000000000400ac0 in main ()
(gdb) 
```

**Comment by alexlarsson** [comment]
Yeah, there is no debug info from the base yocto layer. Need to figure out how to get that.

**Comment by thiblahute** [comment]
> Yeah, there is no debug info from the base yocto layer. Need to figure out how to get that.

A, ok, that is quite annoying :)

**Comment by thiblahute** [comment]
Anything news on that? Do you know what should be done here?

**Comment by alexlarsson** [comment]
We need to build debuginfo rpms in yocto and install them in the base. I don't think it will be super hard, but it will increase the size of the debug stuff quite a bit.

**Comment by thiblahute** [comment]
This still exists on latest Sdk.
